name: Evento frontend

on:
  push:
    branches: ["main"]
    paths:
      - "client/**"
      - ".github/workflows/frontend.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "client/**"
      - ".github/workflows/frontend.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup the code on github machine
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Run linting
        run: |
          cd client
          npm run lint

<<<<<<< HEAD
      #      - name: Run unit tests
      #        run: |
      #          cd client
      #          npm test --watch=false --browsers=ChromeHeadless
=======
#      - name: Run unit tests
#        run: |
#          cd client
#          npm test --watch=false --browsers=ChromeHeadless
>>>>>>> 1de262c (update workflow to fix errors)

      - name: Build angular app
        run: |
          cd client
<<<<<<< HEAD
          npm run build
=======
          npm run build 
>>>>>>> 1de262c (update workflow to fix errors)

      - name: Push docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ayamneelmaini/evento-client
          tags: latest
          registry: docker.io
          dockerfile: client/Dockerfile
          directory: client
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
